name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write  # ✅ required for OIDC-based PyPI publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==1.8.3

      - name: Install dependencies from lockfile
        run: |
          poetry install --no-root --no-interaction --no-ansi

      - name: Build package
        run: |
          poetry build

      - name: Check code style with Black
        run: |
          poetry run black --check .

      - name: Run tests
        run: |
          poetry run pytest -q --tb=short

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
